### PR TITLE
Update CI with external test

### PR DESCRIPTION
**Pull request by markaren**

### CODE REVIEW

**Comment by HenningScheufler** [comment]
On Linux it should be /tmp/fmucktmpLy59Ia/resources/mainclass.txt

not 

tmp/fmucktmpLy59Ia/resources/mainclass.txt

for linux a slash needs to be added to resources:
resources_ = "/" + resources_

But I have no idea why SlaveInstance gets the wrong path?

**Comment by markaren** [comment]
It finally works... Linux and Windows runner can't run at the same time..

**Comment by HenningScheufler** [comment]
Could bump the version to 0.1.1 so we can update the template_fmu4j in

https://github.com/Vico-platform/fmu4j_template

**Comment by markaren** [comment]
Done. Template repo has been updated too.

**Pull request merged**
